
def syracuse(U):
    """
    This function implements the Syracuse algorithm, also known as the Syracuse problem.
    It takes an integer U as input and returns a sequence of integers, starting from U,
    until it reaches 1. The sequence is generated by repeatedly applying the following rules:
    - If U is even, divide it by 2.
    - If U is odd, multiply it by 3 and add 1.
    The function prints the sequence of integers as it is generated.

    Parameters:
    U (int): The starting integer for the Syracuse sequence.

    Returns:
    None. The function prints the generated sequence of integers.
    """
    while U != 1:
        if U % 2 == 0:
            U = U // 2
        else:
            U = 3 * U + 1
        print(U, end=" ")

U = int(input("Enter a number: "))
syracuse(U)